### ISSUE TITLE
Would you allow me to link to your CSS files 

### ISSUE THREAD

**Issue by Zolfax** [Mask1nen/Mask1nen.github.io#1]
Hi,

I'm doing a wiki on https://github.com/Zolfax/zolfax.github.io/wiki/CSS to use CSS with dub+ and am currently asking for good CSS files to add there.
However I don't want to link them without permission at all.
Would you mind me linking your CSS files?

Greetings,
Andy

**Comment by Mask1nen** [comment]
Not at all, you can link them. Glad they're getting used for something!

________________________________
Från: Zolfax <notifications@github.com>
Skickat: den 18 april 2017 00:28
Till: Mask1nen/Mask1nen.github.io
Kopia: Subscribed
Ämne: [Mask1nen/Mask1nen.github.io] Would you allow me to link to your CSS files (#1)


Hi,

I'm doing a wiki on https://github.com/Zolfax/zolfax.github.io/wiki/CSS to use CSS with dub+ and am currently asking for good CSS files to add there.

[https://avatars3.githubusercontent.com/u/26218219?v=3&s=400]<https://github.com/Zolfax/zolfax.github.io/wiki/CSS>

Zolfax/zolfax.github.io<https://github.com/Zolfax/zolfax.github.io/wiki/CSS>
github.com
Contribute to zolfax.github.io development by creating an account on GitHub.



However I don't want to link them without permission at all.
Would you mind me linking your CSS files?

Greetings,
Andy

**Comment by Zolfax** [comment]
Thank you, I did!
Feel free to drop by anytime!
